import os

POSTGRES_SERVER = os.environ.get("POSTGRES_SERVER")
POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_DB = os.environ.get("POSTGRES_DB")

SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}" f"@{POSTGRES_SERVER}:5432/{POSTGRES_DB}"

RABBITMQ_SERVER = os.environ.get("RABBITMQ_SERVER")
RABBITMQ_USERNAME = os.environ.get("RABBITMQ_USERNAME")
RABBITMQ_PASSWORD = os.environ.get("RABBITMQ_PASSWORD")
RABBITMQ_PORT = os.environ.get("RABBITMQ_PORT")

REDIS_SERVER = os.environ.get("REDIS_SERVER")
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD")
REDIS_PORT = os.environ.get("REDIS_PORT")

FLOWER_SERVER = os.environ.get("FLOWER_SERVER")
FLOWER_BASIC_AUTH = os.environ.get("FLOWER_BASIC_AUTH")

BASE_URL = os.environ.get("BASE_URL")
